### ISSUE TITLE
Installer doesn't handle non-ASCII characters well

### ISSUE THREAD

**Issue by ondraknezour** [mautic/mautic-spi#2] opened 2015-04-16 18:35 UTC
Installer doesn't works right way with (at least some) non-ASCII characters. Spotted as problem with characters ě and ž in the admin user surname, but there may be others characters and fields, which are not handled correctly.

**Comment by escopecz** [comment] 2015-04-16 19:35
As far as I know there is no input field to add any text into the SPI. There is just one button which downloads Mautic package, unzips it and redirects you to normal Mautic Installation. So the problem is in the Mautic Installation process or did I missed something?

**Comment by ondraknezour** [comment] 2015-04-16 19:56
So I probably missed what SPI stands for - my understanding was, that single page installer is what is seen by user after Mautic download and composer install, as it is mentioned in the Mautic README.md

> Open your browser and complete the installation through the web installer.

**Comment by escopecz** [comment] 2015-04-16 20:28
Nope, this does what is described in this repo [readme](https://github.com/mautic/mautic-spi). I'll close this issue since it isn't related with the SPI script, but with Mautic itself. You can open the same issue in the [Mautic repository](https://github.com/mautic/mautic) even though I think that usernames should contain ASCII characters only. I actually didn't even thought about using non-ASCII characters as username (and I'm also Czech).

**Comment by ondraknezour** [comment] 2015-04-17 01:04
My fault, I confused SPI with the Mautic installer.

However - username != surname, end even if I would not use non ASCII characters in username, it is clear UI fault not to inform user what characters can and what can not be used in given field if some restrictions apply. Username included.

Recreated as Mautic issue here mautic/mautic#325

**Comment by escopecz** [comment] 2015-04-17 13:34
I misread that the issue is about the surname. It should allow non-ASCII chars for the surname. Thanks for your report!

**Closed as completed by escopecz** 2015-04-17 13:34 UTC
